apiVersion: apps/v1
kind: Deployment
metadata:
  name: proverjay
  namespace: proverjay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proverjay
  template:
    metadata:
      labels:
        app: proverjay
    spec:
      containers:
        - name: proverjay
          image: ghcr.io/h3ow3d/proverjay:fc760ae109f5039d7a0b2f06f774bdff3ea2f97d # v0.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
