apiVersion: apps/v1
kind: Deployment
metadata:
  name: proverjay
  namespace: proverjay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proverjay
  template:
    metadata:
      labels:
        app: proverjay
    spec:
      containers:
        - name: proverjay
          image: ghcr.io/h3ow3d/proverjay@sha256:7d9e9868c4d4d7ee1bed07e11ce187d584e99d522bbf73ba133a0077f73f5b9a # v0.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
