apiVersion: apps/v1
kind: Deployment
metadata:
  name: proverjay
  namespace: proverjay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proverjay
  template:
    metadata:
      labels:
        app: proverjay
    spec:
      containers:
        - name: proverjay
          image: ghcr.io/h3ow3d/proverjay:cc9633ffd3ab4aa3b81c341863935f5cd1b1efe7
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
