apiVersion: apps/v1
kind: Deployment
metadata:
  name: proverjay
  namespace: proverjay
  labels:
    app: proverjay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proverjay
  template:
    metadata:
      labels:
        app: proverjay
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: proverjay
          image: harbor.proverjay.test/proverjay/proverjay:af304bfc4159dd945dff0c086a56555f60c556a3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
