apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: require-signed-proverjay-harbor-image
spec:
  validationActions: [Deny]
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: [v1]
        operations: [CREATE, UPDATE]
        resources: [pods]
  matchImageReferences:
    - glob: harbor.proverjay.test/proverjay/proverjay*
  validationConfigurations:
    mutateDigest: true
    verifyDigest: true
    required: true
  attestors:
    - name: release
      cosign:
        key:
          data: |-
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAET3qZhSvLVvrwaQ/XCjV2cFcxmGkP
            rdxy6XFzc5E0717fO+cjApfU+vnbp9cI9uhjzcSXd0PIHjB9fyzqI5nmlw==
            -----END PUBLIC KEY-----
    - name: provenance
      cosign:
        key:
          data: |-
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAET3qZhSvLVvrwaQ/XCjV2cFcxmGkP
            rdxy6XFzc5E0717fO+cjApfU+vnbp9cI9uhjzcSXd0PIHjB9fyzqI5nmlw==
            -----END PUBLIC KEY-----
  attestations:
    - name: slsaProvenance
      intoto:
        type: "https://slsa.dev/provenance/v0.2"
  validations:
    - expression: >-
        (images.containers + images.initContainers + images.ephemeralContainers)
        .filter(image, image.startsWith('harbor.proverjay.test/proverjay/proverjay'))
        .map(image, verifyImageSignatures(image, [attestors.release]))
        .all(result, result > 0)
      message: Harbor proverjay images must be signed by the trusted release key.
    - expression: >-
        (images.containers + images.initContainers + images.ephemeralContainers)
        .filter(image, image.startsWith('harbor.proverjay.test/proverjay/proverjay'))
        .map(image, verifyAttestationSignatures(image, attestations.slsaProvenance, [attestors.provenance]))
        .all(result, result > 0)
      message: Harbor proverjay images must include a SLSA provenance attestation signed by the trusted release key.
