apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: require-signed-proverjay-image
spec:
  validationActions: [Deny]
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: [v1]
        operations: [CREATE, UPDATE]
        resources: [pods]
  matchImageReferences:
    - glob: ghcr.io/h3ow3d/proverjay*
  validationConfigurations:
    mutateDigest: true
    verifyDigest: true
    required: true
  attestors:
    - name: release
      cosign:
        keyless:
          identities:
            - subjectRegExp: "https://github\\.com/h3ow3d/proverjay/\\.github/workflows/ci\\.yaml@refs/tags/v.*"
              issuer: https://token.actions.githubusercontent.com
        ctlog:
          url: https://rekor.sigstore.dev
    - name: provenance
      cosign:
        keyless:
          identities:
            - subjectRegExp: "https://github\\.com/h3ow3d/proverjay/\\.github/workflows/ci\\.yaml@refs/tags/v.*"
              issuer: https://token.actions.githubusercontent.com
        ctlog:
          url: https://rekor.sigstore.dev
  attestations:
    - name: slsaProvenance
      intoto:
        type: "https://slsa.dev/provenance/v0.2"
  validations:
    - expression: >-
        (images.containers + images.initContainers + images.ephemeralContainers)
        .filter(image, image.startsWith('ghcr.io/h3ow3d/proverjay'))
        .map(image, verifyImageSignatures(image, [attestors.release]))
        .all(result, result > 0)
      message: Proverjay images must be signed by the trusted release key.
    - expression: >-
        (images.containers + images.initContainers + images.ephemeralContainers)
        .filter(image, image.startsWith('ghcr.io/h3ow3d/proverjay'))
        .map(image, verifyAttestationSignatures(image, attestations.slsaProvenance, [attestors.provenance]))
        .all(result, result > 0)
      message: Proverjay images must have a SLSA provenance attestation signed by the trusted release key.
