apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-private-harbor-source
  annotations:
    policies.kyverno.io/title: Require Harbor Image Source
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Require all container images in the proverjay namespace to come from the
      local Harbor registry.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-images-from-local-harbor
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - proverjay
      validate:
        message: "All images in the proverjay namespace must come from harbor.proverjay.test."
        pattern:
          spec:
            containers:
              - image: "harbor.proverjay.test/*"
            =(initContainers):
              - image: "harbor.proverjay.test/*"
            =(ephemeralContainers):
              - image: "harbor.proverjay.test/*"
