name: CI

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    name: Test Go app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Show Go version
        run: go version

      - name: Run tests
        run: make test


  docker-build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    needs: test

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to GHCR
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build image
        run: |
          docker build \
            --build-arg VERSION=${{ github.ref_name }} \
            --build-arg COMMIT=${{ github.sha }} \
            --build-arg CREATED=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push image
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Install cosign
        if: startsWith(github.ref, 'refs/tags/v')
        uses: sigstore/cosign-installer@v4.1.0

      - name: Sign image
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          IMAGE_REF: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        run: |
          cosign sign --yes "$IMAGE_REF"
